name: phone_system_app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.2 <4.0.0"

dependencies:
  supabase_flutter: ^2.5.2
  flutter:
    sdk: flutter

  curved_navigation_bar: ^1.0.6
  fluttertoast: ^8.2.10
  image_picker: ^1.0.7
  device_info_plus: ^10.1.2
  audioplayers: ^6.1.0
  open_file: ^3.5.10
  excel: ^2.0.5
  permission_handler: ^10.4.5
  flutter_localization: ^0.2.0
  font_awesome_flutter: ^10.7.0
  get: ^4.6.6
  modal_bottom_sheet: ^3.0.0
  relative_time: ^5.0.0
  sidebarx: ^0.17.1
  auto_size_text_field: ^2.2.3
  pie_chart: ^5.4.0
  flutter_svg: ^2.0.10+1
  auto_size_text: ^3.0.0
  intl: ^0.19.0
  fl_chart: ^0.68.0
  pdf: ^3.10.8
  printing: ^5.12.0
  syncfusion_flutter_pdfviewer: ^26.2.10
  flutter_launcher_icons: ^0.13.1
  universal_html: ^2.2.4
  flutter_local_notifications: ^16.3.0
  timezone: ^0.9.2
  lottie: ^2.7.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  image_path: "assets/images/logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/logo.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"


flutter:
  uses-material-design: true
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/cairo/Cairo-SemiBold.ttf
        - asset: assets/fonts/cairo/Cairo-Regular.ttf
          weight: 600
        - asset: assets/fonts/cairo/Cairo-Bold.ttf
          weight: 700
        - asset: assets/fonts/cairo/Cairo-Light.ttf
          weight: 300
        - asset: assets/fonts/cairo/Cairo-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/cairo/Cairo-Medium.ttf
          weight: 500
  assets:
    - assets/
    - assets/fonts/
    - assets/images/
    - assets/sounds/
